dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python tests/tests.py
env:
  - ARGCOMPLETE=0
  - ARGCOMPLETE=1
matrix:
  include:
    - install:
      - pip install argcomplete
    - install:
      - pip
