matrix:
  include:
  - language: python
    python:
      - "2.7"
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7"
    script:
      - tests/tests.py
  - language: python
    python:
      - "2.7"
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7"
    script:
      - python tests/tests.py
    install:
      - pip install argcomplete
