dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python setup.py test
env:
  - ARGCOMPLETE=0
  - ARGCOMPLETE=1
install:
  - pip install -r requirements.txt
  - "[ \"$ARGCOMPLETE\" -eq 1 ] && pip install argcomplete || :"
